language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tareqrahman/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true tareqrahman/frontend npm run test
