language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tareqrahman/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true tareqrahman/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-eu-west-1-707278591408"
  bucket_path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
